### PR TITLE
Update response.sh

### PR DESCRIPTION
**Pull request by dark-warlord14**
Solution for issue `Question regarding response.sh #5`

### CODE REVIEW

**Comment by shibli2700** [comment]
Thanks for the pull request, I will review it on my test environment and will merge it 👍.

**Comment by dark-warlord14** [comment]
This update changes things for the script that extracts js files.
So checked that script also.
or dont merge this one.
it will fucked uo the workflow maybe.

**Comment by shibli2700** [comment]
Yeah I will review it and will make necessary changes to other scripts if needed...then only I will merge

**Comment by shibli2700** [comment]
I would be closing this request as I have done some performance changes in response.sh and also now you can explicitly define the path to your active subs file. e.g.

```bash
./response.sh sub-dir/alive.txt
```

**Pull request closed without merging**
